openapi: 3.0.0
info:
  version: '2017-08-25'
  x-release: v4
  title: AWS Signer Revocations#signatureTimestamp&platformId&profileVersionArn&jobArn&certificateHashes Signing Jobs API
  description: <p>AWS Signer is a fully managed code signing service to help you ensure the trust and integrity of your code. </p> <p>AWS Signer supports the following applications:</p> <p>With code signing for AWS Lambda, you can sign <a href="http://docs.aws.amazon.com/lambda/latest/dg/">AWS Lambda</a> deployment packages. Integrated support is provided for <a href="http://docs.aws.amazon.com/AmazonS3/latest/gsg/">Amazon S3</a>, <a href="http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/">Amazon CloudWatch</a>, and <a href="http://docs.aws.amazon.com/awscloudtrail/latest/userguide/">AWS CloudTrail</a>. In order to sign code, you create a signing profile and then use Signer to sign Lambda zip files in S3. </p> <p>With code signing for IoT, you can sign code for any IoT device that is supported by AWS. IoT code signing is available for <a href="http://docs.aws.amazon.com/freertos/latest/userguide/">Amazon FreeRTOS</a> and <a href="http://docs.aws.amazon.com/iot/latest/developerguide/">AWS IoT Device Management</a>, and is integrated with <a href="http://docs.aws.amazon.com/acm/latest/userguide/">AWS Certificate Manager (ACM)</a>. In order to sign code, you import a third-party code signing certificate using ACM, and use that to sign updates in Amazon FreeRTOS and AWS IoT Device Management. </p> <p>With code signing for containers …(TBD)</p> <p>For more information about AWS Signer, see the <a href="https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html">AWS Signer Developer Guide</a>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: signer
  x-aws-signingName: signer
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/signer-2017-08-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://signer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The signer multi-region endpoint
- url: https://signer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The signer multi-region endpoint
- url: http://signer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The signer endpoint for China (Beijing) and China (Ningxia)
- url: https://signer.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The signer endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Signing Jobs
paths:
  /signing-jobs/{jobId}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: DescribeSigningJob
      description: 'Returns information about a specific code signing job. You specify the job by using the <code>jobId</code> value that is returned by the <a>StartSigningJob</a> operation. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeSigningJobResponse'
              examples:
                DescribeSigningJob200Example:
                  summary: Default DescribeSigningJob 200 response
                  x-microcks-default: true
                  value:
                    jobId: job-abc12345
                    source: example-value
                    signingMaterial: example-value
                    platformId: AWSLambda-SHA384-ECDSA
                    platformDisplayName: AWSLambda-SHA384-ECDSA
                    profileName: MySigningProfile
                    profileVersion: MySigningProfile
                    overrides: example-value
                    signingParameters: example-value
                    createdAt: example-value
                    completedAt: example-value
                    signatureExpiresAt: example-value
                    requestedBy: example-value
                    status: Active
                    statusReason: Active
                    revocationRecord: example-value
                    signedObject: example-value
                    jobOwner: job-abc12345
                    jobInvoker: job-abc12345
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                DescribeSigningJob480Example:
                  summary: Default DescribeSigningJob 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                DescribeSigningJob481Example:
                  summary: Default DescribeSigningJob 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                DescribeSigningJob482Example:
                  summary: Default DescribeSigningJob 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
              examples:
                DescribeSigningJob483Example:
                  summary: Default DescribeSigningJob 483 response
                  x-microcks-default: true
                  value: example-value
      parameters:
      - name: jobId
        in: path
        required: true
        description: The ID of the signing job on input.
        schema:
          type: string
      summary: Amazon Describe Signing Job
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Signing Jobs
  /signing-jobs:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListSigningJobs
      description: 'Lists all your signing jobs. You can use the <code>maxResults</code> parameter to limit the number of signing jobs that are returned in the response. If additional jobs remain to be listed, code signing returns a <code>nextToken</code> value. Use this value in subsequent calls to <code>ListSigningJobs</code> to fetch the remaining values. You can continue calling <code>ListSigningJobs</code> with your <code>maxResults</code> parameter and with new values that code signing returns in the <code>nextToken</code> parameter until all of your signing jobs have been returned. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSigningJobsResponse'
              examples:
                ListSigningJobs200Example:
                  summary: Default ListSigningJobs 200 response
                  x-microcks-default: true
                  value:
                    jobs: job-abc12345
                    nextToken: example-value
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListSigningJobs480Example:
                  summary: Default ListSigningJobs 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListSigningJobs481Example:
                  summary: Default ListSigningJobs 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ListSigningJobs482Example:
                  summary: Default ListSigningJobs 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
              examples:
                ListSigningJobs483Example:
                  summary: Default ListSigningJobs 483 response
                  x-microcks-default: true
                  value: example-value
      parameters:
      - name: status
        in: query
        required: false
        description: A status value with which to filter your results.
        schema:
          type: string
          enum:
          - InProgress
          - Failed
          - Succeeded
      - name: platformId
        in: query
        required: false
        description: The ID of microcontroller platform that you specified for the distribution of your code image.
        schema:
          type: string
      - name: requestedBy
        in: query
        required: false
        description: The IAM principal that requested the signing job.
        schema:
          type: string
      - name: maxResults
        in: query
        required: false
        description: 'Specifies the maximum number of items to return in the response. Use this parameter when paginating results. If additional items exist beyond the number you specify, the <code>nextToken</code> element is set in the response. Use the <code>nextToken</code> value in a subsequent request to retrieve additional items. '
        schema:
          type: integer
          minimum: 1
          maximum: 25
      - name: nextToken
        in: query
        required: false
        description: String for specifying the next set of paginated results to return. After you receive a response with truncated results, use this parameter in a subsequent request. Set it to the value of <code>nextToken</code> from the response that you just received.
        schema:
          type: string
      - name: isRevoked
        in: query
        required: false
        description: Filters results to return only signing jobs with revoked signatures.
        schema:
          type: boolean
      - name: signatureExpiresBefore
        in: query
        required: false
        description: Filters results to return only signing jobs with signatures expiring before a specified timestamp.
        schema:
          type: string
          format: date-time
      - name: signatureExpiresAfter
        in: query
        required: false
        description: Filters results to return only signing jobs with signatures expiring after a specified timestamp.
        schema:
          type: string
          format: date-time
      - name: jobInvoker
        in: query
        required: false
        description: Filters results to return only signing jobs initiated by a specified IAM entity.
        schema:
          type: string
          pattern: ^[0-9]{12}$
          minLength: 12
          maxLength: 12
      summary: Amazon List Signing Jobs
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Signing Jobs
    post:
      operationId: StartSigningJob
      description: '<p>Initiates a signing job to be performed on the code provided. Signing jobs are viewable by the <code>ListSigningJobs</code> operation for two years after they are performed. Note the following requirements: </p> <ul> <li> <p> You must create an Amazon S3 source bucket. For more information, see <a href="http://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html">Creating a Bucket</a> in the <i>Amazon S3 Getting Started Guide</i>. </p> </li> <li> <p>Your S3 source bucket must be version enabled.</p> </li> <li> <p>You must create an S3 destination bucket. Code signing uses your S3 destination bucket to write your signed code.</p> </li> <li> <p>You specify the name of the source and destination buckets when calling the <code>StartSigningJob</code> operation.</p> </li> <li> <p>You must also specify a request token that identifies your request to code signing.</p> </li> </ul> <p>You can call the <a>DescribeSigningJob</a> and the <a>ListSigningJobs</a> actions after you call <code>StartSigningJob</code>.</p> <p>For a Java example that shows how to use this action, see <a href="https://docs.aws.amazon.com/signer/latest/developerguide/api-startsigningjob.html">StartSigningJob</a>.</p>'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartSigningJobResponse'
              examples:
                StartSigningJob200Example:
                  summary: Default StartSigningJob 200 response
                  x-microcks-default: true
                  value:
                    jobId: job-abc12345
                    jobOwner: job-abc12345
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                StartSigningJob480Example:
                  summary: Default StartSigningJob 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                StartSigningJob481Example:
                  summary: Default StartSigningJob 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                StartSigningJob482Example:
                  summary: Default StartSigningJob 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                StartSigningJob483Example:
                  summary: Default StartSigningJob 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                StartSigningJob484Example:
                  summary: Default StartSigningJob 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
              examples:
                StartSigningJob485Example:
                  summary: Default StartSigningJob 485 response
                  x-microcks-default: true
                  value: example-value
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - source
              - destination
              - profileName
              - clientRequestToken
              properties:
                source:
                  description: An <code>S3Source</code> object that contains information about the S3 bucket where you saved your unsigned code.
                  type: object
                  properties:
                    s3:
                      allOf:
                      - $ref: '#/components/schemas/S3Source'
                      - description: The <code>S3Source</code> object.
                destination:
                  description: Points to an <code>S3Destination</code> object that contains information about your S3 bucket.
                  type: object
                  properties:
                    s3:
                      allOf:
                      - $ref: '#/components/schemas/S3Destination'
                      - description: The <code>S3Destination</code> object.
                profileName:
                  description: The name of the signing profile.
                  type: string
                  pattern: ^[a-zA-Z0-9_]{2,}
                  minLength: 2
                  maxLength: 64
                clientRequestToken:
                  description: String that identifies the signing request. All calls after the first that use this token return the same response as the first call.
                  type: string
                profileOwner:
                  description: The AWS account ID of the signing profile owner.
                  type: string
                  pattern: ^[0-9]{12}$
                  minLength: 12
                  maxLength: 12
            examples:
              StartSigningJobRequestExample:
                summary: Default StartSigningJob request
                x-microcks-default: true
                value:
                  source:
                    s3: example-value
                  destination:
                    s3: example-value
                  profileName: MySigningProfile
                  clientRequestToken: example-value
                  profileOwner: MySigningProfile
      summary: Amazon Start Signing Job
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Signing Jobs
  /signing-jobs/{jobId}/revoke:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      operationId: RevokeSignature
      description: Changes the state of a signing job to REVOKED. This indicates that the signature is no longer valid.
      responses:
        '200':
          description: Success
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                RevokeSignature480Example:
                  summary: Default RevokeSignature 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                RevokeSignature481Example:
                  summary: Default RevokeSignature 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                RevokeSignature482Example:
                  summary: Default RevokeSignature 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                RevokeSignature483Example:
                  summary: Default RevokeSignature 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
              examples:
                RevokeSignature484Example:
                  summary: Default RevokeSignature 484 response
                  x-microcks-default: true
                  value: example-value
      parameters:
      - name: jobId
        in: path
        required: true
        description: ID of the signing job to be revoked.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - reason
              properties:
                jobOwner:
                  description: AWS account ID of the job owner.
                  type: string
                  pattern: ^[0-9]{12}$
                  minLength: 12
                  maxLength: 12
                reason:
                  description: The reason for revoking the signing job.
                  type: string
                  minLength: 1
                  maxLength: 500
            examples:
              RevokeSignatureRequestExample:
                summary: Default RevokeSignature request
                x-microcks-default: true
                value:
                  jobOwner: job-abc12345
                  reason: example-value
      summary: Amazon Revoke Signature
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Signing Jobs
  /signing-jobs/with-payload:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: SignPayload
      description: Signs a binary payload and returns a signature envelope.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignPayloadResponse'
              examples:
                SignPayload200Example:
                  summary: Default SignPayload 200 response
                  x-microcks-default: true
                  value:
                    jobId: job-abc12345
                    jobOwner: job-abc12345
                    metadata: example-value
                    signature: example-value
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                SignPayload480Example:
                  summary: Default SignPayload 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                SignPayload481Example:
                  summary: Default SignPayload 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                SignPayload482Example:
                  summary: Default SignPayload 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                SignPayload483Example:
                  summary: Default SignPayload 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
              examples:
                SignPayload484Example:
                  summary: Default SignPayload 484 response
                  x-microcks-default: true
                  value: example-value
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - profileName
              - payload
              - payloadFormat
              properties:
                profileName:
                  description: The name of the signing profile.
                  type: string
                  pattern: ^[a-zA-Z0-9_]{2,}
                  minLength: 2
                  maxLength: 64
                profileOwner:
                  description: The AWS account ID of the profile owner.
                  type: string
                  pattern: ^[0-9]{12}$
                  minLength: 12
                  maxLength: 12
                payload:
                  description: Specifies the object digest (hash) to sign.
                  type: string
                  minLength: 1
                  maxLength: 4096
                payloadFormat:
                  description: Payload content type
                  type: string
            examples:
              SignPayloadRequestExample:
                summary: Default SignPayload request
                x-microcks-default: true
                value:
                  profileName: MySigningProfile
                  profileOwner: MySigningProfile
                  payload: example-value
                  payloadFormat: example-value
      summary: Amazon Sign Payload
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Signing Jobs
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    ProfileName:
      type: string
      pattern: ^[a-zA-Z0-9_]{2,}
      minLength: 2
      maxLength: 64
    RequestedBy:
      type: string
    SigningJob:
      type: object
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: The ID of the signing job.
        source:
          allOf:
          - $ref: '#/components/schemas/Source'
          - description: A <code>Source</code> that contains information about a signing job's code image source.
        signedObject:
          allOf:
          - $ref: '#/components/schemas/SignedObject'
          - description: A <code>SignedObject</code> structure that contains information about a signing job's signed code image.
        signingMaterial:
          allOf:
          - $ref: '#/components/schemas/SigningMaterial'
          - description: A <code>SigningMaterial</code> object that contains the Amazon Resource Name (ARN) of the certificate used for the signing job.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that the signing job was created.
        status:
          allOf:
          - $ref: '#/components/schemas/SigningStatus'
          - description: The status of the signing job.
        isRevoked:
          allOf:
          - $ref: '#/components/schemas/bool'
          - description: Indicates whether the signing job is revoked.
        profileName:
          allOf:
          - $ref: '#/components/schemas/ProfileName'
          - description: The name of the signing profile that created a signing job.
        profileVersion:
          allOf:
          - $ref: '#/components/schemas/ProfileVersion'
          - description: The version of the signing profile that created a signing job.
        platformId:
          allOf:
          - $ref: '#/components/schemas/PlatformId'
          - description: The unique identifier for a signing platform.
        platformDisplayName:
          allOf:
          - $ref: '#/components/schemas/DisplayName'
          - description: The name of a signing platform.
        signatureExpiresAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the signature of a signing job expires.
        jobOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The AWS account ID of the job owner.
        jobInvoker:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The AWS account ID of the job invoker.
      description: Contains information about a signing job.
    ListSigningJobsResponse:
      type: object
      properties:
        jobs:
          allOf:
          - $ref: '#/components/schemas/SigningJobs'
          - description: A list of your signing jobs.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: String for specifying the next set of paginated results.
    EncryptionAlgorithm:
      type: string
      enum:
      - RSA
      - ECDSA
    Metadata:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    StartSigningJobResponse:
      type: object
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: The ID of your signing job.
        jobOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The AWS account ID of the signing job owner.
    StatusReason:
      type: string
    String:
      type: string
    InternalServiceErrorException: {}
    CertificateArn:
      type: string
    Source:
      type: object
      properties:
        s3:
          allOf:
          - $ref: '#/components/schemas/S3Source'
          - description: The <code>S3Source</code> object.
      description: An <code>S3Source</code> object that contains information about the S3 bucket where you saved your unsigned code.
    NextToken:
      type: string
    DisplayName:
      type: string
    PlatformId:
      type: string
    AccessDeniedException: {}
    Blob:
      type: string
    JobId:
      type: string
    SignPayloadResponse:
      type: object
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: Unique identifier of the signing job.
        jobOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The AWS account ID of the job owner.
        metadata:
          allOf:
          - $ref: '#/components/schemas/Metadata'
          - description: Information including the signing profile ARN and the signing job ID. Clients use metadata to signature records, for example, as annotations added to the signature manifest inside an OCI registry.
        signature:
          allOf:
          - $ref: '#/components/schemas/Blob'
          - description: A cryptographic signature.
    ProfileVersion:
      type: string
      pattern: ^[a-zA-Z0-9]{10}$
      minLength: 10
      maxLength: 10
    ImageFormat:
      type: string
      enum:
      - JSON
      - JSONEmbedded
      - JSONDetached
    S3Destination:
      type: object
      properties:
        bucketName:
          allOf:
          - $ref: '#/components/schemas/BucketName'
          - description: Name of the S3 bucket.
        prefix:
          allOf:
          - $ref: '#/components/schemas/Prefix'
          - description: An Amazon S3 prefix that you can use to limit responses to those that begin with the specified prefix.
      description: The name and prefix of the S3 bucket where code signing saves your signed objects.
    SigningMaterial:
      type: object
      required:
      - certificateArn
      properties:
        certificateArn:
          allOf:
          - $ref: '#/components/schemas/CertificateArn'
          - description: The Amazon Resource Name (ARN) of the certificates that is used to sign your code.
      description: The ACM certificate that is used to sign your code.
    ResourceNotFoundException: {}
    SigningJobRevocationRecord:
      type: object
      properties:
        reason:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A caller-supplied reason for revocation.
        revokedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time of revocation.
        revokedBy:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identity of the revoker.
      description: Revocation information for a signing job.
    DescribeSigningJobResponse:
      type: object
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: The ID of the signing job on output.
        source:
          allOf:
          - $ref: '#/components/schemas/Source'
          - description: The object that contains the name of your S3 bucket or your raw code.
        signingMaterial:
          allOf:
          - $ref: '#/components/schemas/SigningMaterial'
          - description: The Amazon Resource Name (ARN) of your code signing certificate.
        platformId:
          allOf:
          - $ref: '#/components/schemas/PlatformId'
          - description: The microcontroller platform to which your signed code image will be distributed.
        platformDisplayName:
          allOf:
          - $ref: '#/components/schemas/DisplayName'
          - description: A human-readable name for the signing platform associated with the signing job.
        profileName:
          allOf:
          - $ref: '#/components/schemas/ProfileName'
          - description: The name of the profile that initiated the signing operation.
        profileVersion:
          allOf:
          - $ref: '#/components/schemas/ProfileVersion'
          - description: The version of the signing profile used to initiate the signing job.
        overrides:
          allOf:
          - $ref: '#/components/schemas/SigningPlatformOverrides'
          - description: A list of any overrides that were applied to the signing operation.
        signingParameters:
          allOf:
          - $ref: '#/components/schemas/SigningParameters'
          - description: 'Map of user-assigned key-value pairs used during signing. These values contain any information that you specified for use in your signing job. '
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Date and time that the signing job was created.
        completedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Date and time that the signing job was completed.
        signatureExpiresAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Thr expiration timestamp for the signature generated by the signing job.
        requestedBy:
          allOf:
          - $ref: '#/components/schemas/RequestedBy'
          - description: The IAM principal that requested the signing job.
        status:
          allOf:
          - $ref: '#/components/schemas/SigningStatus'
          - description: Status of the signing job.
        statusReason:
          allOf:
          - $ref: '#/components/schemas/StatusReason'
          - description: String value that contains the status reason.
        revocationRecord:
          allOf:
          - $ref: '#/components/schemas/SigningJobRevocationRecord'
          - description: A revocation record if the signature generated by the signing job has been revoked. Contains a timestamp and the ID of the IAM entity that revoked the signature.
        signedObject:
          allOf:
          - $ref: '#/components/schemas/SignedObject'
          - description: Name of the S3 bucket where the signed code image is saved by code signing.
        jobOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The AWS account ID of the job owner.
        jobInvoker:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: The IAM entity that initiated the signing job.
    Prefix:
      type: string
    SigningJobs:
      type: array
      items:
        $ref: '#/components/schemas/SigningJob'
    SigningPlatformOverrides:
      type: object
      properties:
        signingConfiguration:
          allOf:
          - $ref: '#/components/schemas/SigningConfigurationOverrides'
          - description: A signing configuration that overrides the default encryption or hash algorithm of a signing job.
        signingImageFormat:
          allOf:
          - $ref: '#/components/schemas/ImageFormat'
          - description: A signed image is a JSON object. When overriding the default signing platform configuration, a customer can select either of two signing formats, <code>JSONEmbedded</code> or <code>JSONDetached</code>. (A third format value, <code>JSON</code>, is reserved for future use.) With <code>JSONEmbedded</code>, the signing image has the payload embedded in it. With <code>JSONDetached</code>, the payload is not be embedded in the signing image.
      description: Any overrides that are applied to the signing configuration of a code signing platform.
    S3Source:
      type: object
      required:
      - bucketName
      - key
      - version
      properties:
        bucketName:
          allOf:
          - $ref: '#/components/schemas/BucketName'
          - description: Name of the S3 bucket.
        key:
          allOf:
          - $ref: '#/components/schemas/Key'
          - description: Key name of the bucket object that contains your unsigned code.
        version:
          allOf:
          - $ref: '#/components/schemas/Version'
          - description: Version of your source image in your version enabled S3 bucket.
      description: Information about the S3 bucket where you saved your unsigned code.
    S3SignedObject:
      type: object
      properties:
        bucketName:
          allOf:
          - $ref: '#/components/schemas/BucketName'
          - description: Name of the S3 bucket.
        key:
          allOf:
          - $ref: '#/components/schemas/Key'
          - description: Key name that uniquely identifies a signed code image in your bucket.
      description: The S3 bucket name and key where code signing saved your signed code image.
    Key:
      type: string
    SigningStatus:
      type: string
      enum:
      - InProgress
      - Failed
      - Succeeded
    Version:
      type: string
    SigningParameterValue:
      type: string
    ThrottlingException: {}
    SigningParameters:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SigningParameterValue'
    ValidationException: {}
    HashAlgorithm:
      type: string
      enum:
      - SHA1
      - SHA256
    TooManyRequestsException: {}
    SignedObject:
      type: object
      properties:
        s3:
          allOf:
          - $ref: '#/components/schemas/S3SignedObject'
          - description: The <code>S3SignedObject</code>.
      description: Points to an <code>S3SignedObject</code> object that contains information about your signed code image.
    bool:
      type: boolean
    Timestamp:
      type: string
      format: date-time
    SigningConfigurationOverrides:
      type: object
      properties:
        encryptionAlgorithm:
          allOf:
          - $ref: '#/components/schemas/EncryptionAlgorithm'
          - description: A specified override of the default encryption algorithm that is used in a code signing job.
        hashAlgorithm:
          allOf:
          - $ref: '#/components/schemas/HashAlgorithm'
          - description: A specified override of the default hash algorithm that is used in a code signing job.
      description: A signing configuration that overrides the default encryption or hash algorithm of a signing job.
    BucketName:
      type: string
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/signer/
x-hasEquivalentPaths: true
